server {
    listen 80;
    server_name 51.210.15.92 lftg.info www.lftg.info lftg.netetfix.fr www.lftg.netetfix.fr;
    client_max_body_size 50M;

    location /map {
        proxy_pass http://172.18.0.1:8080/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://lftg-frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }

    location /health {
        proxy_pass http://lftg-backend:3001;
        proxy_set_header Host $host;
    }

    location /docs {
        proxy_pass http://lftg-backend:3001;
        proxy_set_header Host $host;
    }

    location /api {
        proxy_pass http://lftg-backend:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }

    location /socket.io {
        proxy_pass http://lftg-backend:3001/socket.io;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location /uploads {
        proxy_pass http://lftg-backend:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
